"""Unit tests for database models"""

import pytest
from datetime import datetime
from database.models import Session as SessionModel, Message, Settings, Document, DocumentChunk
import uuid


class TestSessionModel:
    """Tests for Session model"""
    
    def test_session_creation(self):
        """Test session creation with explicit values"""
        test_id = str(uuid.uuid4())
        session = SessionModel(id=test_id, title="Test Session")
        assert session.id == test_id
        assert session.title == "Test Session"
    
    def test_session_auto_id_generation(self):
        """Test session auto-generates ID when not provided"""
        session = SessionModel(title="Test")
        # ID should be generated by default factory or on insert
        assert session.title == "Test"
    
    def test_session_custom_id(self):
        """Test session with custom ID"""
        custom_id = "custom-123"
        session = SessionModel(id=custom_id, title="Chat")
        assert session.id == custom_id
        assert session.title == "Chat"
    
    def test_session_repr(self):
        """Test session string representation"""
        session = SessionModel(id="123", title="Chat")
        repr_str = repr(session)
        assert "Session" in repr_str
        assert "123" in repr_str


class TestMessageModel:
    """Tests for Message model"""
    
    def test_message_creation(self):
        """Test message creation"""
        message = Message(
            session_id="session-123",
            role="user",
            content="Hello"
        )
        assert message.session_id == "session-123"
        assert message.role == "user"
        assert message.content == "Hello"
    
    def test_message_with_tokens(self):
        """Test message with token tracking"""
        message = Message(
            session_id="session-123",
            role="assistant",
            content="Response",
            tokens_used=150
        )
        assert message.tokens_used == 150
        assert message.role == "assistant"
        assert message.content == "Response"
    
    def test_message_role_user(self):
        """Test message with user role"""
        message = Message(
            session_id="session-123",
            role="user",
            content="Test"
        )
        assert message.role == "user"
    
    def test_message_role_assistant(self):
        """Test message with assistant role"""
        message = Message(
            session_id="session-123",
            role="assistant",
            content="Test"
        )
        assert message.role == "assistant"
    
    def test_message_repr(self):
        """Test message string representation"""
        message = Message(
            session_id="session-123",
            role="user",
            content="Test"
        )
        repr_str = repr(message)
        assert "Message" in repr_str
        assert "session-123" in repr_str


class TestSettingsModel:
    """Tests for Settings model"""
    
    def test_settings_creation_with_defaults(self, test_db):
        """Test settings creation with default values"""
        # Create and insert into database to apply defaults
        settings = Settings()
        test_db.add(settings)
        test_db.commit()
        test_db.refresh(settings)
        
        assert settings.model_name == "qwen3:8b"
        assert settings.provider == "ollama"
        assert settings.temperature == 0.7
        assert settings.top_p == 0.9
        assert settings.top_k == 40
    
    def test_settings_custom_model(self):
        """Test settings with custom model name"""
        settings = Settings(model_name="qwen3:32b")
        assert settings.model_name == "qwen3:32b"
    
    def test_settings_custom_temperature(self):
        """Test settings with custom temperature"""
        settings = Settings(temperature=0.5)
        assert settings.temperature == 0.5
    
    def test_settings_custom_values(self):
        """Test settings with custom values"""
        settings = Settings(
            model_name="qwen3:32b",
            temperature=0.5,
            top_k=50
        )
        assert settings.model_name == "qwen3:32b"
        assert settings.temperature == 0.5
        assert settings.top_k == 50
    
    def test_settings_custom_provider(self):
        """Test settings with custom provider"""
        settings = Settings(provider="openai")
        assert settings.provider == "openai"
    
    def test_settings_repr(self):
        """Test settings string representation"""
        settings = Settings(model_name="test-model")
        repr_str = repr(settings)
        assert "Settings" in repr_str
        assert "test-model" in repr_str


class TestDocumentModel:
    """Tests for Document model"""
    
    def test_document_creation(self):
        """Test document creation"""
        doc_id = str(uuid.uuid4())
        document = Document(
            id=doc_id,
            filename="test.pdf",
            file_type="pdf",
            content="Test content"
        )
        assert document.id == doc_id
        assert document.filename == "test.pdf"
        assert document.file_type == "pdf"
        assert document.content == "Test content"
    
    def test_document_with_session(self):
        """Test document associated with session"""
        document = Document(
            id=str(uuid.uuid4()),
            filename="test.pdf",
            file_type="pdf",
            content="Test",
            session_id="session-123"
        )
        assert document.session_id == "session-123"
    
    def test_document_chunk_count(self):
        """Test document with chunk count"""
        document = Document(
            id=str(uuid.uuid4()),
            filename="test.pdf",
            file_type="pdf",
            content="Test",
            chunk_count=5
        )
        assert document.chunk_count == 5


class TestDocumentChunkModel:
    """Tests for DocumentChunk model"""
    
    def test_document_chunk_creation(self):
        """Test document chunk creation"""
        chunk = DocumentChunk(
            id=str(uuid.uuid4()),
            document_id="doc-123",
            chunk_index=0,
            content="Chunk content"
        )
        assert chunk.document_id == "doc-123"
        assert chunk.chunk_index == 0
        assert chunk.content == "Chunk content"
    
    def test_document_chunk_with_embedding(self):
        """Test document chunk with embedding"""
        chunk = DocumentChunk(
            id=str(uuid.uuid4()),
            document_id="doc-123",
            chunk_index=0,
            content="Content",
            embedding="[0.1, 0.2, 0.3]",
            tokens=50
        )
        assert chunk.embedding == "[0.1, 0.2, 0.3]"
        assert chunk.tokens == 50
    
    def test_document_creation(self):
        """Test document creation"""
        doc = Document(
            id="doc-123",
            filename="test.pdf",
            file_type="pdf",
            content="Test content"
        )
        assert doc.id == "doc-123"
        assert doc.filename == "test.pdf"
        assert doc.file_type == "pdf"
        assert doc.content == "Test content"
        assert doc.chunk_count == 0
    
    def test_document_with_session(self):
        """Test document associated with session"""
        doc = Document(
            filename="file.pdf",
            file_type="pdf",
            content="Content",
            session_id="session-123"
        )
        assert doc.session_id == "session-123"
    
    def test_document_repr(self):
        """Test document string representation"""
        doc = Document(
            filename="test.pdf",
            file_type="pdf",
            content="Test"
        )
        assert "Document" in repr(doc)
        assert "test.pdf" in repr(doc)


class TestDocumentChunkModel:
    """Tests for DocumentChunk model"""
    
    def test_chunk_creation(self):
        """Test chunk creation"""
        chunk = DocumentChunk(
            document_id="doc-123",
            chunk_index=0,
            content="Chunk content"
        )
        assert chunk.document_id == "doc-123"
        assert chunk.chunk_index == 0
        assert chunk.content == "Chunk content"
    
    def test_chunk_with_embedding(self):
        """Test chunk with embedding"""
        chunk = DocumentChunk(
            document_id="doc-123",
            chunk_index=0,
            content="Content",
            embedding="[0.1, 0.2, 0.3]",
            tokens=100
        )
        assert chunk.embedding == "[0.1, 0.2, 0.3]"
        assert chunk.tokens == 100
    
    def test_chunk_repr(self):
        """Test chunk string representation"""
        chunk = DocumentChunk(
            document_id="doc-123",
            chunk_index=0,
            content="Test"
        )
        assert "DocumentChunk" in repr(chunk)
        assert "doc-123" in repr(chunk)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
